name: Push to GitLab CI

on: [push]

jobs:
  build:
    env:
      BRANCH: master
      DEST_BRANCH: github
      GITLAB_REPO: 'https://code.il2.dsop.io/chkodama/test-upstream-github.git'
      GITLAB_KEY: ${{ secrets.GITLAB_PUSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: "${{ env.BRANCH }}"
          fetch-depth: 0
      - name: prep and push mirror
        run: |
          echo 'echo ${{ env.GITLAB_KEY }}' > ./creds.sh
          chmod 770 ./creds.sh
          git config --global credential.helper cache
          git config --global core.askPass ./creds.sh
          git remote add mirror "${{ env.GITLAB_REPO }}"
          git push -u mirror "${{ env.BRANCH }}":"${{ env.DEST_BRANCH }}"
